apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: fibonacci-app-k8s-dot-com-tls
spec:
  secretName: fibonacci-app-k8s-dot-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: fibonacci-app-k8s.com
  dnsNames:
    - fibonacci-app-k8s.com
    - www.fibonacci-app-k8s.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - fibonacci-app-k8s.com
          - www.fibonacci-app-k8s.com
